version: '3.6'

services:

  chatgpt:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    platform: linux/amd64
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY=000000000000000'
      - 'OPENAI_API_HOST=http://api:8000'

  api:
    build: .
    volumes:
      - ./models:/models
    ports:
      - 8000:8000
    environment:
      - MODEL=/models/7B/gpt4all-lora-quantized.ggml
